### ISSUE TITLE
Code First approach in Entity Framework

### ISSUE THREAD

**Issue by chinarosesz** [tiagoln/BulkExtensions#10]
Before, I was using Database first approach to generate the DB context and the models, using Bulk operations worked great. Today, I'm switching to using Code First approach in Entity Framework where I create the database context and the database models in C#, which then auto generates the tables for me if it hasn't been created yet. I successfully did this when calling SaveChanges, but when I tried to call BulkInsert, it throws this error. 

Do you know if BulkExtensions supports code first approach?

```
Unhandled Exception: System.InvalidOperationException: Cannot access destination table '[dbo].[VsoBuildDefinitionTasks]'. ---> System.Data.SqlClient.SqlException: Invalid object name 'dbo.VsoBuildDefinitionTasks'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at System.Data.SqlClient.SqlBulkCopy.RunParser(BulkCopySimpleResultSet bulkCopyHandler)
   at System.Data.SqlClient.SqlBulkCopy.CreateAndExecuteInitialQueryAsync(BulkCopySimpleResultSet& result)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestAsync(CancellationToken cts, TaskCompletionSource`1 source)
   --- End of inner exception stack trace ---
   at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestAsync(CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalAsync(CancellationToken ctoken)
   at System.Data.SqlClient.SqlBulkCopy.WriteRowSourceToServerAsync(Int32 columnCount, CancellationToken ctoken)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServer(IDataReader reader)
   at EntityFramework.BulkExtensions.Commons.Extensions.BulkInsertExtension.BulkInsertToTable[TEntity](IDbContextWrapper context, IList`1 entities, String tableName, Operation operationType, BulkOptions options)
   at EntityFramework.BulkExtensions.Commons.BulkOperations.BulkInsert.EntityFramework.BulkExtensions.Commons.BulkOperations.IBulkOperation.CommitTransaction[TEntity](IDbContextWrapper context, IEnumerable`1 collection, BulkOptions options)
   at EntityFramework.BulkExtensions.BulkExtensions.BulkInsert[TEntity](DbContext context, IEnumerable`1 entities, InsertOptions options)
   at VsoBuildDefinitionPump.BuildDefinitionTasksPump.Run() in D:\dev\DES.CDID.DataPipeline\src\VsoBuildDefinitionPump\BuildDefinitionTaskPump.cs:line 39
   at VsoBuildDefinitionPump.Program.Main(String[] args) in D:\dev\DES.CDID.DataPipeline\src\VsoBuildDefinitionPump\Program.cs:line 15
Press any key to continue . . .
```

**Comment by tiagoln** [comment]
As a matter of fact, I've developed this library and tested it using Code First, only later in development I tested it with database first. I use this library in a few projects at my work with Code First approach and it works fine. I'll take a look at this stack trace to see if I find what could be wrong. If you could post the model entity you are trying to insert it would be very helpful.

**Comment by chinarosesz** [comment]
Ah ok good to know, then I'm totally doing something wrong. I'm still ramping up and learning how to use code first approach. Here is what I created just to get things working so I understand how stuff works. I think I need to keep on digging. 

```
public class BuildDefinitionTasksPump
    {
        public void Run()
        {
            VsoBuildDefinitionTask task = new VsoBuildDefinitionTask
            {
                DefinitionType = null,
                DisplayName = "hi hi",
                Enabled = true,
                Id = Guid.NewGuid(),
                VersionSpec = "1adlgjk"
            };

            List<VsoBuildDefinitionTask> tasks = new List<VsoBuildDefinitionTask>();
            tasks.Add(task);

            using (DataIngestionDbContext db = new DataIngestionDbContext())
            {
                db.BulkInsert(tasks);
            }
        }
    }

public class DataIngestionDbContext : DbContext
    {
        private static string sqlDataIngestionServerAdminPassword;

        public DbSet<VsoBuildDefinitionTask> VsoBuildDefinitionTasks { get; set; }

        public DataIngestionDbContext()
        {
            string originalConnectionString = ConfigurationManager.ConnectionStrings["DataIngestionEntities"].ConnectionString;

            EntityConnectionStringBuilder entityBuilder = new EntityConnectionStringBuilder(originalConnectionString);
            DbProviderFactory factory = DbProviderFactories.GetFactory(entityBuilder.Provider);

            DbConnectionStringBuilder providerBuilder = factory.CreateConnectionStringBuilder();
            providerBuilder.ConnectionString = entityBuilder.ProviderConnectionString;
            providerBuilder.Add("Password", SqlDataIngestionServerAdminPassword);

            this.Database.Connection.ConnectionString = providerBuilder.ConnectionString;

            // Making 5 minutes the default timeout in the base so we don't have to do it on each instance. 
            // We've seen more timeout errors as we increase the number of pumps
            this.Database.CommandTimeout = TimeSpan.FromMinutes(5).Seconds;
        }

        private string SqlDataIngestionServerAdminPassword
        {
            get
            {
                if (sqlDataIngestionServerAdminPassword == null)
                {
                    AzureKeyVaultClient azureKeyVaultClient = new AzureKeyVaultClient();
                    sqlDataIngestionServerAdminPassword = azureKeyVaultClient.GetSqlDataIngestionServerAdminPassword().Result;
                }

                return sqlDataIngestionServerAdminPassword;
            }
        }
    }

    public class VsoBuildDefinitionTask
    {
        public Guid Id { get; set; }

        public string DisplayName { get; set; }

        public bool Enabled { get; set; }

        public string DefinitionType { get; set; }

        public string VersionSpec { get; set; }
    }

```

**Comment by tiagoln** [comment]
Looking at the stack trace the library attempted to insert data in this table 'dbo.VsoBuildDefinitionTasks' but didn't found it, could you look at the database to see if this table exists and have been initialized, or if it has a different name?

**Comment by chinarosesz** [comment]
I'm hoping by running it the first time, it would automatically create the table for me. Which it did when I used SaveChanges, and then I deleted the table, replaced SaveChanges with BulkInsert, and now both of them don't generate the table for me when I ran Main. I think there is something about deploying database/tables with code first that I don't understand.

**Comment by tiagoln** [comment]
Yes, I thought it could be that. When you create you DbContext object you can call the method `DbContext.Database.Initialize(bool force)`, it initializes your database using the initialization strategy you configured for your project without the need to call `SaveChanges()`. You could call it somewhere in your application initialization, so each time your app runs again it creates the database if it doesn't exists.
```c#
using (var db = new MyDbContext())
{
    db.Database.Initialize(false);
}
```

**Comment by chinarosesz** [comment]
I tired the above and that still threw the same error. If I deleted the _MigrationHistory table and then ran the application again, it works.

**Comment by tiagoln** [comment]
That's because it recreates the database if it no longer exists. Delete the tables won't trigger the initializer. I don't know if you delete _MigrationHistory and not the database maybe it can cause problems if you have more tables, couse it uses this table for internal workings. I'd prefere to delete the database. There are more initialization approaches, you should take a look to see what suits your case best. [Database initialization strategy in code first](http://www.entityframeworktutorial.net/code-first/database-initialization-strategy-in-code-first.aspx)
