### ISSUE TITLE
Error when inserting entities that uses TPH

### ISSUE THREAD

**Issue by daveyjay** [tiagoln/BulkExtensions#25]
I have an Entity class that is a base class and 2 subclasses.  Using TPH I have 1 table with a Discriminator column.

I have a list of base class items (not saved to db yet) and am retrieving a subset from that list and creating a new list.  I then loop through this list, updating a foreign Key Id value in the collection as follows. 

Here is my code:

`
var myListOfBaseTypes = list.BaseTypes.Where(p => !p.SomeCondition).ToList();`
`foreach (var baseType in myListOfBaseTypes)`
`{`
`     baseType.OtherTableId = otherTableId;`
`}`
` context.BulkInsert(myListOfBaseTypes);  // this line throws the error`

When attempting to do a bulk insert with the collection of the base type I get the following error:    

`
System.Data.SqlClient.SqlException occurred
  HResult=0x80131904
  Message=Column names in each table must be unique. Column name 'Discriminator' in table '_BaseType_66ad99' is specified more than once.
  Source=Core .Net SqlClient Data Provider
  StackTrace:
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at EntityFramework.BulkExtensions.Commons.BulkOperations.BulkOperation.CommitTransaction[TEntity](IDbContextWrapper context, IEnumerable`1 collection, Operation operation, BulkOptions options)
   at EntityFramework.BulkExtensions.BulkExtensions.BulkInsert[TEntity](DbContext context, IEnumerable`1 entities, InsertOptions options)
   at DataLayer.Repositories.BaseTypeRepository.SaveItems(SaveItemsPackage saveItemsPackage, MyDbContext context) in .....call stack for my code`

Not sure what to do here...the code is not trying to insert sub class entities - I need to insert base class entities.  I can do this with straight EF code using context.BaseTypes.AddRange() but the whole reason am trying to use the BulkInsert is because I have a large set of data and the performance is bad.

**Comment by tiagoln** [comment]
Hi, I'll see what's going on. I have some questions. First: Are you on version 1.4.0? Second: You're using EF 6 or EF Core? Third: can you post the your entities(the BaseType and the childs)? This information will help a lot =D

**Comment by daveyjay** [comment]
Hi there - thanks for the quick response. :-)

I am on version 1.4.0 of EntityFramework.BulkExtensions.EFCore.

I seem to have found what was causing that error.  In my code I have to explicitly assign the value for the Discriminator.  I believe this has something to do with it.  When I remove this code, the Bulk insert works and I don't get that error.  In my Discriminator column in the database I end up with the name of the Base class.

Unfortunately for me - I need to keep the existing behaviour where we manually assign the Discriminator value to the name of the sub class when we are instantiating the objects.  I realize that this is not the recommended approach - we should be instantiating instances of the sub class - however we cannot change this right now as it would be a massive rewrite of our code (long and painful story). Mostly we are using the subclasses when retrieving data from the db and use polymorphism to get different behavior.

The error we are getting mentions "column name Discriminator being specified more than once."  This must be because we have a property named Discriminator explicitly in our base class. 

Here is a snippet of our Base `class:`

`public` class Entity`
`{`
  `public int Id {get; set;}`
`}`

`public class BaseClass : Entity`
`{`
   ` public string Property1 {get; set;}`
  `  public string Discriminator {get; set;}`
`}`

As I mentioned, if I use straight ahead EF out of the box this all works fine.  Is it possible to make a feature request to check for the Discriminator being manually assigned?

**Comment by tiagoln** [comment]
I see. Tomorrow I'll try to reproduce a scenario like this to see how I can manage this behavior.

**Comment by daveyjay** [comment]
Thanks for your help!

**Comment by tiagoln** [comment]
@daveyjay  I have released a new version to fix this issue, check it out.

**Comment by daveyjay** [comment]
The new version fixed the issue - everything is working great!

Thanks very much - thanks to your library we have a process that was taking over 2 minutes now working in 26 seconds :-)

**Comment by tiagoln** [comment]
I'm happy to hear that, glad I could help =D
