### ISSUE TITLE
SqlConnection does not support parallel transactions.

### ISSUE THREAD

**Issue by s13n4** [tiagoln/BulkExtensions#28]
Even if I have not started a transaction, trying to BulkInsert 
if (_context.Database.Transaction == null )
 _context.BulkInsertOrUpdate(records, InsertOptions.Default);

gives me an exception.

----
System.Data.Entity.Core.EntityException occurred
  HResult=0x80131501
  Message=An error occurred while starting a transaction on the provider connection. See the inner exception for details.
  Source=EntityFramework
  StackTrace:
   at System.Data.Entity.Core.EntityClient.EntityConnection.BeginDbTransaction(IsolationLevel isolationLevel)
   at System.Data.Entity.Core.EntityClient.EntityConnection.BeginTransaction(IsolationLevel isolationLevel)
   at System.Data.Entity.DbContextTransaction..ctor(EntityConnection connection, IsolationLevel isolationLevel)
   at System.Data.Entity.Database.BeginTransaction(IsolationLevel isolationLevel)
   at Riscosoftware.MIFIR.DAL.Generic.GenericDAL.AddEntities[T](List`1 records) in D:\Craftsmanship\Source\Cesarz-Mifir\Riscosoftware.MIFIR.DAL\Generic\GenericDAL.cs:line 95
   at Riscosoftware.MIFIR.Web.Controllers.Dictionaries.DictMICController.DownloadListMic() in D:\Craftsmanship\Source\Cesarz-Mifir\Riscosoftware.MIFIR.Web\Controllers\Dictionaries\DictMICController.cs:line 68
   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()

Inner Exception 1:
**InvalidOperationException: SqlConnection does not support parallel transactions.**

**Comment by tiagoln** [comment]
Hi there, theoretically this exception is thrown when a BeginTransaction is called before a previous transaction on the context has been committed or rolled back. 

You can check for yourself here at the [DbContextWrapper](https://github.com/tiagoln/BulkExtensions/blob/master/BulkExtensions.Shared/Context/DbContextWrapper.cs) class that the library only begins a transaction if the database transaction is currently null, so you shouldn't need that `if (_context.Database.Transaction == null )` statement you put there, this is rather strange as your transaction is indeed null. 

I see your project is a MVC one, do you use the same context object across different requests or you create a new context object instance for each request? You see, the entity framework DbContext object is not thread safe, so each request should have it's own context instance([Check here](https://msdn.microsoft.com/en-us/library/jj729737(v=vs.113).aspx#Anchor_3)) as you cannot use the same context object in more than one thread, maybe that's the problem here.

Another thing, which entity framework are you using, EF6 or EFCore?

**Comment by s13n4** [comment]
Hi, I checked it once again and you are right. There is nothing wrong with your code. Sorry! And thanks for pointing me out the solution. Regards

**Comment by tiagoln** [comment]
No problem, if you need more info, there is a very good contextualization of this multithread scenario [here](https://stackoverflow.com/a/10588594/8033392).
